// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: hellostream/test.proto

package hellostream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息
type HelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hellostream_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_hellostream_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_hellostream_test_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// 响应消息
type HelloRly struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapField map[uint32]*WikiInfo `protobuf:"bytes,1,rep,name=map_field,json=mapField,proto3" json:"map_field,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HelloRly) Reset() {
	*x = HelloRly{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hellostream_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRly) ProtoMessage() {}

func (x *HelloRly) ProtoReflect() protoreflect.Message {
	mi := &file_hellostream_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRly.ProtoReflect.Descriptor instead.
func (*HelloRly) Descriptor() ([]byte, []int) {
	return file_hellostream_test_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRly) GetMapField() map[uint32]*WikiInfo {
	if x != nil {
		return x.MapField
	}
	return nil
}

type WikiInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WikiId   uint32 `protobuf:"varint,1,opt,name=wiki_id,json=wikiId,proto3" json:"wiki_id,omitempty"`
	WikiName string `protobuf:"bytes,2,opt,name=wiki_name,json=wikiName,proto3" json:"wiki_name,omitempty"`
}

func (x *WikiInfo) Reset() {
	*x = WikiInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hellostream_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WikiInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WikiInfo) ProtoMessage() {}

func (x *WikiInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hellostream_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WikiInfo.ProtoReflect.Descriptor instead.
func (*WikiInfo) Descriptor() ([]byte, []int) {
	return file_hellostream_test_proto_rawDescGZIP(), []int{2}
}

func (x *WikiInfo) GetWikiId() uint32 {
	if x != nil {
		return x.WikiId
	}
	return 0
}

func (x *WikiInfo) GetWikiName() string {
	if x != nil {
		return x.WikiName
	}
	return ""
}

var File_hellostream_test_proto protoreflect.FileDescriptor

var file_hellostream_test_proto_rawDesc = []byte{
	0x0a, 0x16, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x1e, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa0, 0x01, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x6c, 0x79, 0x12, 0x40, 0x0a, 0x09, 0x6d, 0x61, 0x70, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x6c, 0x79, 0x2e, 0x4d, 0x61, 0x70,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x61, 0x70, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x1a, 0x52, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x2e, 0x57, 0x69, 0x6b, 0x69, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x40, 0x0a, 0x08, 0x57, 0x69, 0x6b, 0x69,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x69, 0x6b, 0x69, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x77, 0x69, 0x6b, 0x69, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x77, 0x69, 0x6b, 0x69, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x77, 0x69, 0x6b, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x3e, 0x0a, 0x04, 0x54, 0x65,
	0x73, 0x74, 0x12, 0x36, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x46, 0x5a, 0x18, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0xca, 0x02, 0x13, 0x47, 0x72, 0x70, 0x63, 0x50, 0x68, 0x70,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0xe2, 0x02, 0x13, 0x47,
	0x72, 0x70, 0x63, 0x50, 0x68, 0x70, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5c, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hellostream_test_proto_rawDescOnce sync.Once
	file_hellostream_test_proto_rawDescData = file_hellostream_test_proto_rawDesc
)

func file_hellostream_test_proto_rawDescGZIP() []byte {
	file_hellostream_test_proto_rawDescOnce.Do(func() {
		file_hellostream_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_hellostream_test_proto_rawDescData)
	})
	return file_hellostream_test_proto_rawDescData
}

var file_hellostream_test_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hellostream_test_proto_goTypes = []interface{}{
	(*HelloReq)(nil), // 0: hellostream.HelloReq
	(*HelloRly)(nil), // 1: hellostream.HelloRly
	(*WikiInfo)(nil), // 2: hellostream.WikiInfo
	nil,              // 3: hellostream.HelloRly.MapFieldEntry
}
var file_hellostream_test_proto_depIdxs = []int32{
	3, // 0: hellostream.HelloRly.map_field:type_name -> hellostream.HelloRly.MapFieldEntry
	2, // 1: hellostream.HelloRly.MapFieldEntry.value:type_name -> hellostream.WikiInfo
	0, // 2: hellostream.Test.Test:input_type -> hellostream.HelloReq
	1, // 3: hellostream.Test.Test:output_type -> hellostream.HelloRly
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hellostream_test_proto_init() }
func file_hellostream_test_proto_init() {
	if File_hellostream_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hellostream_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hellostream_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRly); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hellostream_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WikiInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hellostream_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hellostream_test_proto_goTypes,
		DependencyIndexes: file_hellostream_test_proto_depIdxs,
		MessageInfos:      file_hellostream_test_proto_msgTypes,
	}.Build()
	File_hellostream_test_proto = out.File
	file_hellostream_test_proto_rawDesc = nil
	file_hellostream_test_proto_goTypes = nil
	file_hellostream_test_proto_depIdxs = nil
}
